### ISSUE TITLE
meaningless_label.txt is missing

### ISSUE THREAD

**Issue by Vallxy** [fmehralian/COALA#1]
Thanks for sharing this impressive work.
However, when I tried to run the filter_icon.py, I found the file meaningless_label.txt was missing. Would you mind providing it?

**Comment by fmehralian** [comment]
Thank you for your interest in our work. "meaningless_label.txt," is a component from a previous study, as mentioned in our paper. Here is the link to that:
https://github.com/chenjshnn/LabelDroid/blob/master/meaningless_label.txt

**Comment by Vallxy** [comment]
That works, thanks a lot.
